version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: flask-app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
#      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - DB_URL=postgresql://flask_db_owner:ieph7TqHM8xB@ep-weathered-sunset-a4fear84.us-east-1.aws.neon.tech/flask_db?sslmode=require
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}